### ISSUE TITLE
CloseBy documentation

### ISSUE THREAD

**Issue by powrsurg** [SamsungInternet/support#1]
It would be useful to provide a bit more information on what CloseBy is and how it's supposed to work. Reading that it was supposed to use beacons made me believe that it should be like the NearBy feature built into Android. I set up another device to emit a beacon URL which NearBy notified me of, though CloseBy did not show anything. I do not know if this means that CloseBy was buggy for me, or if it functions differently than I expected.

**Comment by diekus** [comment]
Hi, @powrsurg. Have you enabled the CloseBy extension in the browser? I am detecting beacons with two different devices running the beta. Which app are you using to create a virtual beacon? I can try to reproduce.

![screenshot_20161123-161607](https://cloud.githubusercontent.com/assets/3104648/20588831/2ae5f4b4-b210-11e6-95de-7c6683e2c492.png)
![screenshot_20161123-161604](https://cloud.githubusercontent.com/assets/3104648/20588830/2ae4ca08-b210-11e6-9126-8196f26b40c2.png)

**Comment by powrsurg** [comment]
Yes, I have enabled the extension, I was using the Beacon Toy Android app on my LG G3 which broadcast an Eddystone-URL. With that NearBy detected the broadcast, but CloseBy did not.

**Comment by diekus** [comment]
@powrsurg just double checked, installed BeaconToy on a S7 (the other beacon is a physical estimote beacon) and both Project Magnet and  CloseBy detected them.

Are you still unable to see beacons with CloseBy? If so, have you tried with another app to simulate a beacon and had the same results?

![beaconscloseby](https://cloud.githubusercontent.com/assets/3104648/20791559/7c375380-b7b5-11e6-8095-13adee0ecef4.png)

**Comment by powrsurg** [comment]
@diekus For some reason I can't detect anything from Beacon Toy on my own device so I am broadcasting from an LG G3 I have. It is detected by Project Magnet, shows up as a drop down with NearBy, but does not appear in CloseBy.

I have not tried another simulation tool. Do you have a suggestion?

![samsung](https://cloud.githubusercontent.com/assets/190563/20808079/4ac996ea-b7cf-11e6-8079-73115b520937.png)

Do you offer different beta builds based on the device/provider maybe? The build on my SAMSUNG-SM-G930V in general has been buggy. CloseBy is not detecting anything, and when I've tried to use Push Notifications (something I emailed about as soon as I received beta access, before I saw this issue tracker) crash the browser.

**Comment by diekus** [comment]
@powrsurg can you let me know the subject and date of your email about the push notifications? I have been experiencing some inconsistent behavior  with CloseBy as well. Could you write to me at diego.nzalez@samsung.com . Thanks.

**Comment by poshaughnessy** [comment]
Hi @powrsurg, thank you for reporting this. We've spoken with the team working on CloseBy and the feature is no longer working in the beta due to internal updates. Sorry about that. There is an update to the beta coming very soon that should re-enable it and hopefully work better for you. We'll keep you posted!

**Comment by powrsurg** [comment]
Glad to hear it.

**Comment by poshaughnessy** [comment]
Hi @powrsurg, sorry for the delay getting back to you! Please might you like to try it again since the recent beta update went out? @diekus and I have been giving it a quick test ourselves and it appears to be working again OK for us. Please note, unfortunately it sounds like you will need to uninstall and reinstall the app in order to fix it!

<img src="https://cloud.githubusercontent.com/assets/151207/21811065/258b1cbe-d746-11e6-91c9-e1fb602a91a5.png" width="300px"/>

**Comment by powrsurg** [comment]
@poshaughnessy I just tried on my build (which I have not manually uninstalled and reinstalled) and I am picking up the beacon from Beacon Toy.

I must say, I do like that CloseBy is showing some of the text from the page. That being said, it would be neat if it tweaked the content some.  I assume it's showing the meta description tag if there is one, or text from the page if there is no description. I would suggest trying to tweak that some as the page I tested against had no description and our "Skip to main content" link was shown.

**Comment by jeffprestes** [comment]
Hi @poshaughnessy

I've installed the Samsung Internet today and I am facing the same issue. I have a Galaxy S5 and using Nearby, Chrome and Physical Web app I am able to detect the beacons.
An important note: there's no SIM Card on my phone. I am using only WiFi to navigate. I saw the device tries to access carrier network. Might be this the issue?

Thanks in advance!

**Comment by poshaughnessy** [comment]
Hi @jeffprestes. Eddystone-URL beacons just broadcast (short) URLs, so Physical Web requires network access in order to access the resolver service, to provide the page title, description and icon. I wrote a little bit about that [here](https://medium.com/samsung-internet-dev/bringing-the-real-world-to-your-browser-with-closeby-830cd162547e#60b5) (including about our privacy commitment) and [there's some notes about it here too under 'private networks'](https://mobiforge.com/design-development/eddystone-beacon-technology-and-the-physical-web).

**Comment by jeffprestes** [comment]
Hi @poshaughnessy ,

I see, but later I went to Samsung Ocean São Paulo (http://www.oceanbrasil.com/), actually one day after I'd written to you, and we have tried to use CloseBy using other Samsung devices and we were not able to see the items. I can assure you all of our devices had good internet connection supplied by Samsung office.
But it's OK, the product is in Beta phase and these situations are normal. We are looking ahead and looking forward to make this feature be a success among Samsung customers.
Could I ask you a favor? Would you mind testing a URL for us? Could you set up a Beacon with this URL: https://nvx.bz/3 and see if in your device the CloseBy for this URL is working properly?

Thanks in advance!

**Comment by edstros** [comment]
@poshaughnessy I am also unable to see Physical Web beacons with CloseBy. I am using a BKON A1 beacon broadcasting a url that can be detected with the PHY browser, Nearby and Chrome. Testing device is an LG Nexus 5. I am using Samsung Internet Beta version 5.4.00-48.

**Comment by poshaughnessy** [comment]
@edstros @jeffprestes Apologies for the very slow reply. Having followed up with my colleagues, unfortunately this seems to be due to difficulties with our URL whitelisting, which we're working on improving. In the meantime, you could let me know which URL you're pointing the beacon to, and I can check that with our system (p.oshaughnes [at] samsung [dot] com if you'd like to email). Also if you'd like to, just for temporary testing, you could try for now with a URL that we know should be active, such as https://developer.samsung.com/internet.

**Comment by yshuman1** [comment]
@poshaughnessy Hi, I have had no luck trying to receive URLs to a brand new samsung j3. we are able to receive the notifications on ios chrome widget but not on android. I have tried scanning for the beacons on the samsung phone with no luck. The beacons are from kontakt.io, the samsung has a wifi connection but not a cellular one. Does that matter? Does the phone have to be activated for this to work?

**Comment by poshaughnessy** [comment]
Hi everyone. Very sorry we haven't been quicker following up on this. I've checked again with our colleagues working on CloseBy and they have reiterated this set of base criteria. Please take a look and see if any of these could be the issue?:

https://samsunginter.net/docs/closeby#criteria

If you still have difficulty, please email us with further details to closeby@samsung.com and webadvocacy@samsung.com.
