### ISSUE TITLE
using port to connect to local web server with gearVR not working

### ISSUE THREAD

**Issue by karenstritz** [SamsungInternet/support#4]
I am attempting to connect via USB to localhost:8000. The browser automatically adds http:// to the beginning of the url which prevents me from accessing the file. I also tried using 127.0.0.1:8000 and this works on the standard samsung internet app, but not inside the gearVR which continues to add http:// to the beginning.

Samsung Internet for GearVR version: 4.2.00-14

Samsung Internet version: 5.0.20-45

**Comment by AdaRoseEdwards** [comment]
Thanks for the heads up!

This is an issue we have previously reported, it is annoying. 

One work around I often use is to use ngrok (https://ngrok.com/) to make it available via the ngrok service. 

I hope we can get this issue addressed soon.

I am leaving this issue open so I can notify when the bug is fixed.

**Comment by karenstritz** [comment]
Thank you for the workaround, that did the trick! :) I appreciate the help.

**Comment by poshaughnessy** [comment]
I think this should be fixed now, but if anyone still replicates the issue, please comment here and we can re-open.
