### ISSUE TITLE
HTML5 audio with HLS streaming with DVR timeshift on Samsung Internet

### ISSUE THREAD

**Issue by paulwellnerbou** [SamsungInternet/support#5]
i am trying to make a web based streaming player (http://srv.deutschlandradio.de/themes/streamplayer/index.html) work for Samsung Internet (Samsung's Android stock browser), without success.

The stream plays, but I am unable to control it's position. It seems that Samsung's browser supports basic HLS streaming, but no seeking (nor live playing) of streams with DVR (DVR functionality allows viewers to pause, play, and rewind live streams for a certain time).

For example, audioElement.currentTime always returns 0, and changing it's value, it switches back to 0 every time.

This works fine on other browsers (as documented here: https://www.w3schools.com/tags/av_prop_currenttime.asp).

Is there any documentation on streaming support with DVR window for Samsung Internet?

I posted this question on stackoverflow (http://stackoverflow.com/questions/43014387/html5-audio-with-hls-streaming-with-dvr-timeshift-on-samsung-internet) as well, as Peter O'Shaughnessy suggested (https://medium.com/samsung-internet-dev/introducing-samsung-internet-for-developers-6c3a3be42f72)  ... Maybe there are some workarounds? MediaSourceExtensions are not supported either, as it seems.

Thanks!

**Comment by poshaughnessy** [comment]
Hi @paulwellnerbou. 

I've made a couple of quick tests to check reading and setting currentTime works OK with a standard &lt;video> and &lt;audio> source:

https://github.com/poshaughnessy/streaming-tests

I'm not very familiar with streaming media, so it's tricky right now for me to see where the issue lies. I've tried a couple of other HLS demos such as [Apple's basic stream sample here](https://developer.apple.com/streaming/examples/basic-stream-osx-ios4-3.html) and they seem to work OK.

Please might you be able to help distil this down into a minimal test case? That way I can pass on a bug report to our engineering colleagues. Thanks!

**Comment by paulwellnerbou** [comment]
@poshaughnessy, thanks for your feedback.

Yes, I am able to create a small test case. The linked radio player might serve as well, there is a bit of javascript around encapsulating the player controls, but it is a normal <audio> stream.

The special characteristik of this stream is that it is a live stream (where I understand that `currentTime` can't be changed), but with time shift window, so you should be able to rewind up to two hours back in time of this live stream.
And the Samsung browser does not seem to support this, it assumes that this is just a normal live stream.

I will create a minimal test case for you within the next days.

**Comment by paulwellnerbou** [comment]
Creating a test case helped me narrowing the issue down. Samsung Internet behaves exactly as Chrome. The difference is that Chrome (including Chrome's Web View, it works in an App) does support MediaSourceExtiensions, which are needed to play and rewind/forward within a live HLS stream (using hls.js (https://github.com/video-dev/hls.js), for example.)

**Comment by poshaughnessy** [comment]
Thank you @paulwellnerbou, that's very helpful. Please let me follow up with colleagues about our MediaSourceExtensions support and get back to you!

**Comment by poshaughnessy** [comment]
For reference, here is a demo link to check this:

http://html5-demos.appspot.com/static/media-source.html

In Samsung Internet v5.0 and 5.4 beta, this gives a popup "MediaSource API is not available".

**Comment by paulwellnerbou** [comment]
Ok, so this means that the caniuse information is incorrect ans Samsung Internet does not support MediaSource Extensions?

**Comment by paulwellnerbou** [comment]
@poshaughnessy, can you confirm that? If yes, I will try to get in touch with caniuse.com to fix this information about Samsung Internet and MediaSource Extensions.

**Comment by poshaughnessy** [comment]
Hi @paulwellnerbou. I've been in touch with colleagues and they confirmed that due to compatibility issues, MediaSource Extensions are currently disabled by default in Samsung Internet. (To enable it as an experiment, you would need to go to `internet://flags`, but that comes with the usual experimental flags caution notice).

Apologies that's probably not very helpful for you and sorry it took a while to answer. It would be great if we can arrange caniuse.com to be updated to reflect this. I will update if/when the situation changes.

**Comment by tbutter** [comment]
@poshaughnessy Samsung Internet 5.2 had a flag "Enable Media Source Extension" which enabled MSE. The current beta has the flag "Enable legacy MSE". What does legacy mean in this context? If its deactivated MSE does not work.

**Comment by poshaughnessy** [comment]
@tbutter I heard back from a colleague and it seems like it's the same flag with a new name. Sorry, due to the compatibility issues, it still couldn't be enabled by default.

**Comment by Beraliv** [comment]
In Samsung Internet v7.4, popup with "MediaSource API is not available" is still placed.

Do you plan to support MSE in the future?
